export const CLIENT_COMMANDS = {
  PLAYER_ACTION: 'CMD_PLAYER_ACTION',
  LEAVE_TABLE: 'CMD_LEAVE_TABLE',
} as const;

export const SERVER_EVENTS = {
  HAND_STARTED: 'EV_HAND_STARTED',
  PLAYER_SEATED: 'EV_PLAYER_SEATED',
  TURN_CHANGED: 'EV_TURN_CHANGED',
} as const;
